FROM nginx:latest
LABEL maintainer 'Jairo Nascimento'

RUN echo '<h1>Pagina de apresentação Jairo Nascimento</h1><br><h2>Conteúdo</h2>' > /usr/share/nginx/html/conteudo.html
COPY *.html /usr/share/nginx/html/